import type { LucideIcon } from "lucide-react";
import {
  Images,
  Newspaper,
  Handshake,
  Share2,
  MonitorCog,
  Stethoscope,
  ClipboardList,
} from "lucide-react";

export type CmsModuleKey =
  | "carrossel"
  | "noticias"
  | "exames"
  | "preparos"
  | "convenios"
  | "redes-sociais"
  | "equipamentos";

export type CmsField = {
  name: string;
  label: string;
  type?:
    | "text"
    | "textarea"
    | "url"
    | "number"
    | "date"
    | "datetime-local"
    | "select"
    | "checkbox";
  required?: boolean;
  options?: { label: string; value: string }[];
  help: string;
  example?: string;
  location: string;
  recommendedMax?: number;
  maxLength?: number;
  fullWidth?: boolean;
  richText?: boolean;
};

export type CmsModule = {
  key: CmsModuleKey;
  label: string;
  singular: string;
  table:
    | "carousel_slides"
    | "news_posts"
    | "exams"
    | "preparations"
    | "health_partners"
    | "social_posts"
    | "equipment";
  icon: LucideIcon;
  fields: CmsField[];
};

export type CmsModuleFormConfig = Omit<CmsModule, "icon">;

export const cmsModules: CmsModule[] = [
  {
    key: "carrossel",
    label: "Página inicial",
    singular: "slide",
    table: "carousel_slides",
    icon: Images,
    fields: [
      {
        name: "title",
        label: "Título principal",
        required: true,
        help: "Use uma frase curta e direta.",
        example: "Conheça a INNEURO",
        location: "Aparece em destaque sobre a imagem da página inicial.",
        recommendedMax: 60,
        maxLength: 160,
      },
      {
        name: "description",
        label: "Texto de apoio",
        type: "textarea",
        help: "Explique o destaque em uma ou duas frases.",
        example: "Tecnologia e acolhimento em cada etapa do atendimento.",
        location: "Aparece logo abaixo do título no banner.",
        recommendedMax: 160,
        maxLength: 500,
        fullWidth: true,
      },
      {
        name: "category",
        label: "Categoria",
        help: "Uma palavra que identifica o assunto.",
        example: "Institucional",
        location: "Aparece acima do título.",
        recommendedMax: 30,
        maxLength: 80,
      },
      {
        name: "image_alt",
        label: "Descrição da imagem",
        required: true,
        help: "Descreva o que aparece na foto para pessoas que usam leitor de tela.",
        example: "Fachada da INNEURO em Macapá.",
        location: "Não fica visível; é usada para acessibilidade.",
        recommendedMax: 160,
        maxLength: 240,
      },
      {
        name: "cta_label",
        label: "Texto do botão",
        help: "Diga claramente o que acontece ao clicar.",
        example: "Conhecer a INNEURO",
        location: "Aparece no botão do banner.",
        recommendedMax: 30,
        maxLength: 80,
      },
      {
        name: "cta_url",
        label: "Destino do botão",
        help: "Use um caminho do site, como /sobre, ou uma URL completa.",
        example: "/sobre",
        location: "Define a página aberta pelo botão.",
        maxLength: 500,
      },
      {
        name: "linked_news_id",
        label: "Matéria vinculada",
        type: "select",
        help: "Opcional. Escolha uma notícia publicada ou em preparação.",
        location: "Ao clicar no slide, abre a matéria escolhida.",
        options: [{ label: "Nenhuma matéria", value: "" }],
      },
      {
        name: "open_in_new_tab",
        label: "Abrir em nova aba",
        type: "checkbox",
        help: "Use apenas para links externos. Links do próprio site devem abrir na mesma aba.",
        location: "Comportamento do botão do slide.",
      },
      {
        name: "publish_at",
        label: "Agendar publicação",
        type: "datetime-local",
        help: "Opcional. Escolha quando o conteúdo deve entrar no site.",
        location: "Controla a data de publicação.",
      },
      {
        name: "active",
        label: "Exibir este destaque",
        type: "checkbox",
        help: "Ative para permitir que o destaque apareça no carrossel.",
        location: "Página inicial.",
      },
      {
        name: "sort_order",
        label: "Ordem de exibição",
        type: "number",
        help: "Use 0 para aparecer primeiro, 1 para o segundo e assim por diante.",
        example: "0",
        location: "Define a posição no carrossel.",
      },
    ],
  },
  {
    key: "noticias",
    label: "Notícias",
    singular: "notícia",
    table: "news_posts",
    icon: Newspaper,
    fields: [
      {
        name: "title",
        label: "Título da notícia",
        required: true,
        help: "Informe o assunto principal com linguagem clara.",
        example: "INNEURO amplia atendimento em Macapá",
        location: "Aparece na lista de notícias e no topo da publicação.",
        recommendedMax: 60,
        maxLength: 180,
      },
      {
        name: "slug",
        label: "Endereço da notícia",
        required: true,
        help: "Use letras minúsculas, números e hífens, sem espaços ou acentos.",
        example: "inneuro-amplia-atendimento",
        location: "Forma o endereço /noticias/endereco-da-noticia.",
        maxLength: 120,
      },
      {
        name: "summary",
        label: "Resumo",
        type: "textarea",
        required: true,
        help: "Resuma a notícia em uma ou duas frases.",
        example: "Veja as principais informações desta atualização.",
        location: "Aparece nos cards e abaixo do título da notícia.",
        recommendedMax: 160,
        maxLength: 500,
        fullWidth: true,
      },
      {
        name: "category",
        label: "Categoria",
        help: "Agrupe a publicação por assunto.",
        example: "Institucional",
        location: "Aparece acima do título.",
        recommendedMax: 30,
        maxLength: 80,
      },
      {
        name: "author",
        label: "Autor",
        help: "Informe o nome ou a equipe responsável pelo texto.",
        example: "Equipe INNEURO",
        location: "Identificação editorial da matéria.",
        recommendedMax: 60,
        maxLength: 120,
      },
      {
        name: "content_text",
        label: "Texto completo",
        type: "textarea",
        help: "Escreva em parágrafos curtos. Use os botões de formatação quando necessário.",
        example: "Comece com a informação mais importante...",
        location: "Aparece no corpo da notícia.",
        fullWidth: true,
        richText: true,
      },
      {
        name: "seo_title",
        label: "Título para buscadores",
        help: "Opcional. Se ficar vazio, será usado o título da notícia.",
        example: "Atendimento INNEURO em Macapá",
        location: "Aparece no Google e na aba do navegador.",
        recommendedMax: 60,
        maxLength: 70,
      },
      {
        name: "seo_description",
        label: "Descrição para buscadores",
        type: "textarea",
        help: "Opcional. Resuma a página para resultados de busca.",
        example: "Conheça as novidades e serviços da INNEURO em Macapá.",
        location: "Pode aparecer nos resultados do Google.",
        recommendedMax: 160,
        maxLength: 170,
        fullWidth: true,
      },
      {
        name: "publish_at",
        label: "Agendar publicação",
        type: "datetime-local",
        help: "Opcional. Escolha a data e o horário de publicação.",
        location: "Controla quando a notícia entra no site.",
      },
      {
        name: "featured_on_home",
        label: "Destacar na página inicial",
        type: "checkbox",
        help: "Marque para mostrar a notícia entre os destaques recentes.",
        location: "Página inicial.",
      },
      {
        name: "show_in_carousel",
        label: "Exibir no carrossel",
        type: "checkbox",
        help: "Marque apenas para uma notícia que mereça grande destaque.",
        location: "Carrossel da página inicial.",
      },
    ],
  },
  {
    key: "exames",
    label: "Exames",
    singular: "exame",
    table: "exams",
    icon: Stethoscope,
    fields: [
      {
        name: "name",
        label: "Nome do exame",
        required: true,
        help: "Use o nome pelo qual o paciente procura o exame.",
        example: "Ressonância Magnética",
        location: "Cards, busca e página do exame.",
        recommendedMax: 60,
        maxLength: 160,
      },
      {
        name: "slug",
        label: "Endereço do exame",
        required: true,
        help: "Use letras minúsculas e hífens, sem espaços ou acentos.",
        example: "ressonancia-magnetica",
        location: "Forma o endereço /exames/endereco-do-exame.",
        maxLength: 120,
      },
      {
        name: "modality",
        label: "Modalidade",
        required: true,
        help: "Informe a categoria usada no filtro.",
        example: "Ressonância Magnética",
        location: "Filtro e identificação do card.",
        recommendedMax: 60,
        maxLength: 120,
      },
      {
        name: "modality_slug",
        label: "Identificador da modalidade",
        required: true,
        help: "Normalmente é igual ao endereço do exame.",
        example: "ressonancia-magnetica",
        location: "Filtro interno do catálogo.",
        maxLength: 120,
      },
      {
        name: "short_description",
        label: "Descrição curta",
        type: "textarea",
        required: true,
        help: "Explique de forma objetiva, sem criar promessa médica.",
        example:
          "Modalidade realizada conforme indicação e solicitação médica.",
        location: "Card e topo da página do exame.",
        recommendedMax: 160,
        maxLength: 500,
        fullWidth: true,
      },
      {
        name: "preparation_slug",
        label: "Preparo relacionado",
        help: "Informe o endereço do preparo associado.",
        example: "ressonancia-magnetica",
        location: "Link “Consultar preparo” da página do exame.",
        maxLength: 120,
      },
      {
        name: "purpose",
        label: "Para que serve",
        type: "textarea",
        help: "Use somente informação aprovada pela clínica.",
        location: "Página de detalhes do exame.",
        recommendedMax: 300,
        maxLength: 3000,
        fullWidth: true,
      },
      {
        name: "how_performed",
        label: "Como é realizado",
        type: "textarea",
        help: "Descreva o procedimento de forma simples.",
        location: "Página de detalhes do exame.",
        recommendedMax: 300,
        maxLength: 3000,
        fullWidth: true,
      },
      {
        name: "general_guidance",
        label: "Orientações gerais",
        type: "textarea",
        help: "Não substitua o preparo específico nem orientação médica.",
        location: "Página de detalhes do exame.",
        maxLength: 3000,
        fullWidth: true,
      },
      {
        name: "documents",
        label: "Documentos",
        type: "textarea",
        help: "Liste os documentos solicitados pela clínica.",
        location: "Página de detalhes do exame.",
        maxLength: 2000,
        fullWidth: true,
      },
      {
        name: "icon",
        label: "Ícone",
        type: "select",
        help: "Escolha o símbolo visual da modalidade.",
        location: "Cards de modalidades.",
        options: [
          { label: "Ressonância", value: "magnetic-resonance" },
          { label: "Tomografia", value: "computed-tomography" },
          { label: "Raios X", value: "x-ray" },
          { label: "Medicina Nuclear", value: "nuclear-medicine" },
          { label: "Cintilografia", value: "scintigraphy" },
          { label: "Mapeamento Cerebral", value: "brain-mapping" },
        ],
      },
      {
        name: "featured",
        label: "Destacar na página inicial",
        type: "checkbox",
        help: "Mostra o exame entre as principais modalidades.",
        location: "Página inicial.",
      },
      {
        name: "active",
        label: "Exibir no site",
        type: "checkbox",
        help: "Somente exames publicados e ativos aparecem ao público.",
        location: "Página inicial e catálogo de exames.",
      },
      {
        name: "sort_order",
        label: "Ordem de exibição",
        type: "number",
        help: "Use 0 para aparecer primeiro.",
        example: "0",
        location: "Listas e filtros.",
      },
    ],
  },
  {
    key: "preparos",
    label: "Preparos e horários",
    singular: "preparo",
    table: "preparations",
    icon: ClipboardList,
    fields: [
      {
        name: "name",
        label: "Nome da modalidade",
        required: true,
        help: "Use o mesmo nome exibido no exame relacionado.",
        example: "Ressonância Magnética",
        location: "Catálogo e página de preparo.",
        maxLength: 160,
      },
      {
        name: "slug",
        label: "Endereço do preparo",
        required: true,
        help: "Use letras minúsculas e hífens, sem espaços ou acentos.",
        example: "ressonancia-magnetica",
        location: "Forma o endereço /preparos/endereco-do-preparo.",
        maxLength: 120,
      },
      {
        name: "exam_slug",
        label: "Exame relacionado",
        required: true,
        help: "Informe o endereço do exame associado.",
        example: "ressonancia-magnetica",
        location: "Vínculo entre exame e preparo.",
        maxLength: 120,
      },
      {
        name: "search_terms_text",
        label: "Termos de busca",
        type: "textarea",
        help: "Digite um termo por linha.",
        example: "contraste\njejum\nmetais",
        location: "Pesquisa de preparos.",
        maxLength: 3000,
        fullWidth: true,
      },
      {
        name: "attendance_mode",
        label: "Forma de atendimento",
        type: "select",
        help: "Indique se é por ordem de chegada ou agendamento.",
        location: "Página de preparos.",
        options: [
          { label: "Necessita agendamento", value: "appointment" },
          { label: "Ordem de chegada", value: "walk-in" },
          { label: "Misto", value: "mixed" },
        ],
      },
      {
        name: "attendance_label",
        label: "Texto do atendimento",
        required: true,
        help: "Mensagem curta exibida ao paciente.",
        example: "Necessita agendamento",
        location: "Card e página de preparo.",
        maxLength: 120,
      },
      {
        name: "schedules_text",
        label: "Horários",
        type: "textarea",
        help: "Uma linha por horário: Rótulo | Dias | 07h-12h; 13h-18h.",
        example: "Atendimento | Segunda a sexta-feira | 08h-12h; 13h-18h",
        location: "Contato, Home e página do preparo.",
        maxLength: 8000,
        fullWidth: true,
      },
      {
        name: "preparation_groups_text",
        label: "Orientações de preparo",
        type: "textarea",
        help: "Uma linha por grupo: Título | Aplica-se a | instrução 1; instrução 2 | aviso opcional.",
        example:
          "Exames com contraste | Tomografia com contraste | Jejum de 4 horas; Trazer exames anteriores | Confirme dúvidas com a equipe.",
        location: "Página detalhada do preparo.",
        maxLength: 20000,
        fullWidth: true,
      },
      {
        name: "documents_text",
        label: "Documentos necessários",
        type: "textarea",
        help: "Digite um documento por linha.",
        location: "Página detalhada do preparo.",
        maxLength: 5000,
        fullWidth: true,
      },
      {
        name: "safety_questions_text",
        label: "Informações de segurança",
        type: "textarea",
        help: "Digite uma situação por linha, somente com conteúdo aprovado pela clínica.",
        location: "Página detalhada do preparo.",
        maxLength: 5000,
        fullWidth: true,
      },
      {
        name: "previous_exams_recommended",
        label: "Recomendar exames anteriores",
        type: "checkbox",
        help: "Marque quando a orientação oficial pedir exames anteriores.",
        location: "Página detalhada do preparo.",
      },
      {
        name: "validated_by_clinic",
        label: "Conteúdo validado pela clínica",
        type: "checkbox",
        help: "Confirme somente após revisão responsável da INNEURO.",
        location: "Aviso de validação do preparo.",
      },
      {
        name: "last_reviewed_at",
        label: "Data da última revisão",
        type: "date",
        required: true,
        help: "Informe quando a clínica revisou estas orientações.",
        location: "Página do preparo.",
      },
      {
        name: "active",
        label: "Exibir no site",
        type: "checkbox",
        help: "Somente preparos publicados e ativos aparecem ao público.",
        location: "Catálogo de preparos.",
      },
      {
        name: "sort_order",
        label: "Ordem de exibição",
        type: "number",
        help: "Use 0 para aparecer primeiro.",
        example: "0",
        location: "Catálogo de preparos.",
      },
    ],
  },
  {
    key: "convenios",
    label: "Convênios",
    singular: "convênio ou parceria",
    table: "health_partners",
    icon: Handshake,
    fields: [
      {
        name: "name",
        label: "Nome exibido",
        required: true,
        help: "Use o nome completo da operadora ou parceria.",
        example: "CAPE Saúde — CAPESESP",
        location: "Aparece na página de convênios.",
        recommendedMax: 60,
        maxLength: 160,
      },
      {
        name: "slug",
        label: "Identificador",
        required: true,
        help: "Use letras minúsculas e hífens, sem espaços ou acentos.",
        example: "cape-saude-capesesp",
        location: "Usado internamente para identificar o cadastro.",
        maxLength: 120,
      },
      {
        name: "website_url",
        label: "Site institucional",
        type: "url",
        help: "Opcional. Informe o endereço completo, começando com https://.",
        example: "https://www.exemplo.com.br/",
        location: "Referência institucional do cadastro.",
        maxLength: 500,
      },
      {
        name: "logo_alt",
        label: "Descrição da logo",
        required: true,
        help: "Use o nome correto da marca, por exemplo “Logo SulAmérica”.",
        example: "Logo SulAmérica",
        location: "Acessibilidade da Home e da página de convênios.",
        recommendedMax: 120,
        maxLength: 240,
      },
      {
        name: "notes",
        label: "Observações",
        type: "textarea",
        help: "Informações administrativas úteis e aprovadas.",
        location: "Cadastro do convênio.",
        maxLength: 2000,
        fullWidth: true,
      },
      {
        name: "restrictions",
        label: "Restrições",
        type: "textarea",
        help: "Informe somente restrições confirmadas pela INNEURO.",
        location: "Cadastro do convênio.",
        maxLength: 2000,
        fullWidth: true,
      },
      {
        name: "kind",
        label: "Classificação",
        type: "select",
        help: "Escolha como a marca deve ser identificada.",
        location: "Aparece abaixo da marca.",
        options: [
          { label: "Convênio", value: "convenio" },
          { label: "Parceria", value: "parceria" },
        ],
      },
      {
        name: "active",
        label: "Exibir no site",
        type: "checkbox",
        help: "Marque para mostrar este cadastro ao público.",
        location: "Home e página de convênios.",
      },
      {
        name: "sort_order",
        label: "Ordem de exibição",
        type: "number",
        help: "Use 0 para aparecer primeiro, 1 para o segundo e assim por diante.",
        example: "0",
        location: "Lista de convênios.",
      },
    ],
  },
  {
    key: "redes-sociais",
    label: "Contatos e redes sociais",
    singular: "chamada social",
    table: "social_posts",
    icon: Share2,
    fields: [
      {
        name: "network",
        label: "Rede",
        required: true,
        help: "Informe a rede social.",
        example: "Instagram",
        location: "Card da publicação.",
        recommendedMax: 30,
        maxLength: 80,
      },
      {
        name: "url",
        label: "Link da publicação",
        type: "url",
        required: true,
        help: "Cole o endereço completo da publicação.",
        example: "https://www.instagram.com/p/...",
        location: "Abre ao clicar no card.",
        maxLength: 500,
      },
      {
        name: "title",
        label: "Título",
        required: true,
        help: "Explique o assunto em uma frase curta.",
        example: "Cuidados antes do exame",
        location: "Título do card.",
        recommendedMax: 60,
        maxLength: 180,
      },
      {
        name: "callout",
        label: "Texto curto",
        type: "textarea",
        help: "Escreva uma chamada simples para a publicação.",
        example: "Confira as orientações da nossa equipe.",
        location: "Descrição do card.",
        recommendedMax: 300,
        maxLength: 500,
        fullWidth: true,
      },
      {
        name: "occurred_at",
        label: "Data da publicação",
        type: "datetime-local",
        help: "Informe quando o conteúdo foi publicado.",
        location: "Organização cronológica.",
      },
      {
        name: "cta_label",
        label: "Texto do botão",
        help: "Diga o que acontece ao clicar.",
        example: "Ver publicação",
        location: "Botão do card.",
        recommendedMax: 30,
        maxLength: 80,
      },
      {
        name: "featured",
        label: "Destacar",
        type: "checkbox",
        help: "Marque para dar mais visibilidade a este item.",
        location: "Página inicial.",
      },
      {
        name: "active",
        label: "Exibir no site",
        type: "checkbox",
        help: "Marque para permitir a exibição pública.",
        location: "Página inicial.",
      },
      {
        name: "sort_order",
        label: "Ordem de exibição",
        type: "number",
        help: "Use 0 para aparecer primeiro.",
        example: "0",
        location: "Lista de publicações.",
      },
    ],
  },
  {
    key: "equipamentos",
    label: "Equipamentos",
    singular: "equipamento",
    table: "equipment",
    icon: MonitorCog,
    fields: [
      {
        name: "name",
        label: "Nome do equipamento",
        required: true,
        help: "Use o nome pelo qual o público reconhece o equipamento.",
        example: "Ressonância magnética",
        location: "Seção institucional de equipamentos.",
        recommendedMax: 60,
        maxLength: 160,
      },
      {
        name: "modality",
        label: "Modalidade do exame",
        required: true,
        help: "Informe a modalidade relacionada.",
        example: "Ressonância magnética",
        location: "Identificação do equipamento.",
        recommendedMax: 60,
        maxLength: 120,
      },
      {
        name: "description",
        label: "Descrição",
        type: "textarea",
        required: true,
        help: "Explique a função do equipamento sem criar promessa médica.",
        example: "Equipamento utilizado para aquisição de imagens detalhadas.",
        location: "Texto do card institucional.",
        recommendedMax: 300,
        maxLength: 5000,
        fullWidth: true,
      },
      {
        name: "featured",
        label: "Destacar",
        type: "checkbox",
        help: "Marque para dar mais visibilidade ao equipamento.",
        location: "Seção institucional.",
      },
      {
        name: "active",
        label: "Exibir no site",
        type: "checkbox",
        help: "Marque para permitir a exibição pública.",
        location: "Seção institucional.",
      },
      {
        name: "sort_order",
        label: "Ordem de exibição",
        type: "number",
        help: "Use 0 para aparecer primeiro.",
        example: "0",
        location: "Lista de equipamentos.",
      },
    ],
  },
];

export function getCmsModule(key: string) {
  return cmsModules.find((module) => module.key === key);
}
