import { z } from "zod";

const optionalText = z.string().trim().max(5000).optional().or(z.literal(""));
const slug = z
  .string()
  .trim()
  .min(1)
  .max(120)
  .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/);
const optionalUrl = z.string().trim().url().optional().or(z.literal(""));

export const moduleSchemas = {
  carrossel: z.object({
    title: z.string().trim().min(1).max(160),
    description: optionalText,
    category: z.string().trim().max(80).optional(),
    image_alt: z.string().trim().min(1).max(240),
    cta_label: z.string().trim().max(80).optional(),
    cta_url: z.string().trim().max(500).optional(),
    linked_news_id: z.string().uuid().optional().or(z.literal("")),
    open_in_new_tab: z.boolean(),
    publish_at: z.string().optional(),
    active: z.boolean(),
    sort_order: z.number().int().min(0).max(9999),
  }),
  noticias: z.object({
    title: z.string().trim().min(1).max(180),
    slug,
    summary: z.string().trim().min(1).max(500),
    category: z.string().trim().max(80).optional(),
    author: z.string().trim().max(120).optional(),
    content_text: z.string().trim().max(30000).optional(),
    seo_title: z.string().trim().max(70).optional(),
    seo_description: z.string().trim().max(170).optional(),
    publish_at: z.string().optional(),
    featured_on_home: z.boolean(),
    show_in_carousel: z.boolean(),
  }),
  exames: z.object({
    name: z.string().trim().min(1).max(160),
    slug,
    modality: z.string().trim().min(1).max(120),
    modality_slug: slug,
    short_description: z.string().trim().min(1).max(500),
    preparation_slug: slug.optional().or(z.literal("")),
    purpose: z.string().trim().max(3000).optional(),
    how_performed: z.string().trim().max(3000).optional(),
    general_guidance: z.string().trim().max(3000).optional(),
    documents: z.string().trim().max(2000).optional(),
    icon: z.enum([
      "magnetic-resonance",
      "computed-tomography",
      "x-ray",
      "nuclear-medicine",
      "scintigraphy",
      "brain-mapping",
    ]),
    featured: z.boolean(),
    active: z.boolean(),
    sort_order: z.number().int().min(0).max(9999),
  }),
  preparos: z.object({
    name: z.string().trim().min(1).max(160),
    slug,
    exam_slug: slug,
    search_terms_text: z.string().trim().max(3000).optional(),
    attendance_mode: z.enum(["walk-in", "appointment", "mixed"]),
    attendance_label: z.string().trim().min(1).max(120),
    use_general_schedule: z.boolean(),
    override_days_text: z.string().trim().max(500).optional(),
    override_periods_text: z.string().trim().max(300).optional(),
    schedule_note: z.string().trim().max(500).optional(),
    schedules_text: z.string().trim().max(8000).optional(),
    preparation_groups_text: z.string().trim().max(20000).optional(),
    documents_text: z.string().trim().max(5000).optional(),
    safety_questions_text: z.string().trim().max(5000).optional(),
    previous_exams_recommended: z.boolean(),
    validated_by_clinic: z.boolean(),
    last_reviewed_at: z.string().date(),
    active: z.boolean(),
    sort_order: z.number().int().min(0).max(9999),
  }),
  convenios: z.object({
    name: z.string().trim().min(1).max(160),
    slug,
    website_url: optionalUrl,
    logo_alt: z.string().trim().min(1).max(240),
    notes: z.string().trim().max(2000).optional(),
    restrictions: z.string().trim().max(2000).optional(),
    kind: z.enum(["convenio", "parceria"]),
    active: z.boolean(),
    sort_order: z.number().int().min(0).max(9999),
  }),
  "redes-sociais": z.object({
    network: z.string().trim().min(1).max(80),
    url: z.string().trim().url(),
    title: z.string().trim().min(1).max(180),
    callout: optionalText,
    occurred_at: z.string().optional(),
    cta_label: z.string().trim().max(80).optional(),
    featured: z.boolean(),
    active: z.boolean(),
    sort_order: z.number().int().min(0).max(9999),
  }),
  equipamentos: z.object({
    name: z.string().trim().min(1).max(160),
    modality: z.string().trim().min(1).max(120),
    description: z.string().trim().min(1).max(5000),
    featured: z.boolean(),
    active: z.boolean(),
    sort_order: z.number().int().min(0).max(9999),
  }),
};
